export const data = [
  {
    author: 'uutils',
    name: 'coreutils',
    avatar: 'https://github.com/uutils.png',
    url: 'https://github.com/uutils/coreutils',
    description: 'Cross-platform Rust rewrite of the GNU coreutils',
    language: 'Rust',
    languageColor: '#dea584',
    stars: 7143,
    forks: 565,
    currentPeriodStars: 76,
  },
  {
    author: 'microsoft',
    name: 'CSS-Exchange',
    avatar: 'https://github.com/microsoft.png',
    url: 'https://github.com/microsoft/CSS-Exchange',
    description: 'Exchange Server support tools and scripts',
    language: 'PowerShell',
    languageColor: '#012456',
    stars: 679,
    forks: 135,
    currentPeriodStars: 107,
  },
  {
    author: 'jellyfin',
    name: 'jellyfin',
    avatar: 'https://github.com/jellyfin.png',
    url: 'https://github.com/jellyfin/jellyfin',
    description: 'The Free Software Media System',
    language: 'C#',
    languageColor: '#178600',
    stars: 9907,
    forks: 1008,
    currentPeriodStars: 12,
  },
  {
    author: 'nvm-sh',
    name: 'nvm',
    avatar: 'https://github.com/nvm-sh.png',
    url: 'https://github.com/nvm-sh/nvm',
    description: 'Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions',
    language: 'Shell',
    languageColor: '#89e051',
    stars: 47298,
    forks: 4767,
    currentPeriodStars: 28,
  },
  {
    author: 'tuist',
    name: 'tuist',
    avatar: 'https://github.com/tuist.png',
    url: 'https://github.com/tuist/tuist',
    description: '🚀 Create, maintain, and interact with Xcode projects at scale',
    language: 'Swift',
    languageColor: '#ffac45',
    stars: 1449,
    forks: 139,
    currentPeriodStars: 8,
  },
  {
    author: 'microsoft',
    name: 'onnxruntime',
    avatar: 'https://github.com/microsoft.png',
    url: 'https://github.com/microsoft/onnxruntime',
    description: 'ONNX Runtime: cross-platform, high performance ML inferencing and training accelerator',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 4198,
    forks: 968,
    currentPeriodStars: 8,
  },
  {
    author: 'LeCoupa',
    name: 'awesome-cheatsheets',
    avatar: 'https://github.com/LeCoupa.png',
    url: 'https://github.com/LeCoupa/awesome-cheatsheets',
    description:
      '👩‍💻👨‍💻 Awesome cheatsheets for popular programming languages, frameworks and development tools. They include everything you should know in one single file.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 16251,
    forks: 2804,
    currentPeriodStars: 298,
  },
  {
    author: 'qier222',
    name: 'YesPlayMusic',
    avatar: 'https://github.com/qier222.png',
    url: 'https://github.com/qier222/YesPlayMusic',
    description: '高颜值的第三方网易云播放器，支持 Windows / macOS / Linux',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 6185,
    forks: 564,
    currentPeriodStars: 250,
  },
  {
    author: 'GorvGoyl',
    name: 'Clone-Wars',
    avatar: 'https://github.com/GorvGoyl.png',
    url: 'https://github.com/GorvGoyl/Clone-Wars',
    description:
      '70+ open-source clones of popular sites like Airbnb, Amazon, Instagram, Netflix, Tiktok, Spotify, Whatsapp, Youtube etc. See source code, demo links, tech stack, github stars.',
    stars: 1283,
    forks: 74,
    currentPeriodStars: 269,
  },
  {
    author: 'sherlock-project',
    name: 'sherlock',
    avatar: 'https://github.com/sherlock-project.png',
    url: 'https://github.com/sherlock-project/sherlock',
    description: '🔎 Hunt down social media accounts by username across social networks',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 22725,
    forks: 2279,
    currentPeriodStars: 402,
  },
  {
    author: 'd2l-ai',
    name: 'd2l-zh',
    avatar: 'https://github.com/d2l-ai.png',
    url: 'https://github.com/d2l-ai/d2l-zh',
    description: '《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被全球175所大学采用教学。',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 20734,
    forks: 5249,
    currentPeriodStars: 109,
  },
  {
    author: '2368693074',
    name: '49shouting',
    avatar: 'https://github.com/2368693074.png',
    url: 'https://github.com/2368693074/49shouting',
    description: '联通挂机任务积分脚本',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 93,
    forks: 508,
    currentPeriodStars: 16,
  },
  {
    author: 'ossu',
    name: 'computer-science',
    avatar: 'https://github.com/ossu.png',
    url: 'https://github.com/ossu/computer-science',
    description: '🎓 Path to a free self-taught education in Computer Science!',
    stars: 79330,
    forks: 11325,
    currentPeriodStars: 545,
  },
  {
    author: 'files-community',
    name: 'Files',
    avatar: 'https://github.com/files-community.png',
    url: 'https://github.com/files-community/Files',
    description: 'A modern file explorer that pushes the boundaries of the platform.',
    language: 'C#',
    languageColor: '#178600',
    stars: 7680,
    forks: 450,
    currentPeriodStars: 45,
  },
  {
    author: 'hashicorp',
    name: 'consul',
    avatar: 'https://github.com/hashicorp.png',
    url: 'https://github.com/hashicorp/consul',
    description:
      'Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.',
    language: 'Go',
    languageColor: '#00ADD8',
    stars: 21629,
    forks: 3651,
    currentPeriodStars: 65,
  },
  {
    author: 'mobilecoinfoundation',
    name: 'mobilecoin',
    avatar: 'https://github.com/mobilecoinfoundation.png',
    url: 'https://github.com/mobilecoinfoundation/mobilecoin',
    description: 'Private payments for mobile devices.',
    language: 'Rust',
    languageColor: '#dea584',
    stars: 292,
    forks: 43,
    currentPeriodStars: 5,
  },
  {
    author: 'ryanmcdermott',
    name: 'clean-code-javascript',
    avatar: 'https://github.com/ryanmcdermott.png',
    url: 'https://github.com/ryanmcdermott/clean-code-javascript',
    description: '🛁 Clean Code concepts adapted for JavaScript',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 47794,
    forks: 5797,
    currentPeriodStars: 78,
  },
  {
    author: 'fuck-xuexiqiangguo',
    name: 'Fuck-XueXiQiangGuo',
    avatar: 'https://github.com/fuck-xuexiqiangguo.png',
    url: 'https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo',
    description: '学习强国 懒人刷分工具 自动学习',
    stars: 7235,
    forks: 1717,
    currentPeriodStars: 31,
  },
  {
    author: 'bradtraversy',
    name: 'design-resources-for-developers',
    avatar: 'https://github.com/bradtraversy.png',
    url: 'https://github.com/bradtraversy/design-resources-for-developers',
    description:
      'Curated list of design and UI resources from stock photos, web templates, CSS frameworks, UI libraries, tools and much more',
    stars: 24705,
    forks: 6093,
    currentPeriodStars: 106,
  },
  {
    author: 'leonardomso',
    name: '33-js-concepts',
    avatar: 'https://github.com/leonardomso.png',
    url: 'https://github.com/leonardomso/33-js-concepts',
    description: '📜 33 concepts every JavaScript developer should know.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 37071,
    forks: 4500,
    currentPeriodStars: 140,
  },
  {
    author: '521xueweihan',
    name: 'HelloGitHub',
    avatar: 'https://github.com/521xueweihan.png',
    url: 'https://github.com/521xueweihan/HelloGitHub',
    description: 'Find pearls on open-source seashore 分享 GitHub 上有趣、入门级的开源项目',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 37934,
    forks: 5618,
    currentPeriodStars: 73,
  },
  {
    author: 'felangel',
    name: 'bloc',
    avatar: 'https://github.com/felangel.png',
    url: 'https://github.com/felangel/bloc',
    description: 'A predictable state management library that helps implement the BLoC design pattern',
    language: 'Dart',
    languageColor: '#00B4AB',
    stars: 6671,
    forks: 1702,
    currentPeriodStars: 12,
  },
  {
    author: 'ampproject',
    name: 'amphtml',
    avatar: 'https://github.com/ampproject.png',
    url: 'https://github.com/ampproject/amphtml',
    description: 'The AMP web component framework.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 14212,
    forks: 3771,
    currentPeriodStars: 6,
  },
  {
    author: 'KaLendsi',
    name: 'CVE-2021-1732-Exploit',
    avatar: 'https://github.com/KaLendsi.png',
    url: 'https://github.com/KaLendsi/CVE-2021-1732-Exploit',
    description: 'CVE-2021-1732 Exploit',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 203,
    forks: 42,
    currentPeriodStars: 51,
  },
  {
    author: 'pavlobu',
    name: 'deskreen',
    avatar: 'https://github.com/pavlobu.png',
    url: 'https://github.com/pavlobu/deskreen',
    description: 'Deskreen turns any device with a web browser into a secondary screen for your computer',
    language: 'TypeScript',
    languageColor: '#2b7489',
    stars: 9179,
    forks: 365,
    currentPeriodStars: 157,
  },
];
